
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew cmake
brew doxygen
brew gdbm
brew gettext
brew git
brew icu4c
brew jemalloc
brew libevent
brew libtermkey
brew libtool
brew libuv
brew libvterm
brew libyaml
brew mas
brew msgpack
brew n
brew node
brew openssl
brew perl
brew pkg-config
brew python
brew readline
brew reattach-to-user-namespace
brew ruby
brew sqlite
brew tmux
brew unibilium
brew vim
brew xz
brew yarn --without-node

tap homebrew/bundle

tap caskroom/cask
cask alfred
cask discord
cask gitter
cask hipchat
cask iterm2
cask rocket-chat
cask skype
cask slack
cask sourcetree
cask ubersicht
cask vagrant

tap caskroom/fonts

tap argon/mas

tap atlassian/tap
brew atlassian-plugin-sdk

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 405843582 Alfred (1.2)
appstore 715768417 Microsoft Remote Desktop (8.0.27246)
appstore 1176895641 Spark (1.1.0)
