
# tap repositories and their packages

tap homebrew/core
brew autoconf
brew automake
brew azure-cli
brew berkeley-db
brew brotli
brew c-ares
brew cake
brew cmake
brew cscope
brew curl
brew docker
brew dos2unix
brew dotnet
brew doxygen
brew gcc
brew gdbm
brew gettext
brew git
brew git-gui
brew git-lfs
brew gmp
brew go
brew icu4c
brew isl
brew jemalloc
brew libev
brew libevent
brew libidn2
brew libmetalink
brew libmpc
brew libssh2
brew libtermkey
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libyaml
brew lua
brew m4
brew macvim --HEAD
brew mas
brew mono
brew mpdecimal
brew mpfr
brew msgpack
brew n
brew ncurses
brew nghttp2
brew openldap
brew openssl@1.1
brew pcre
brew pcre2
brew perl
brew pkg-config
brew python@3.8
brew python@3.9
brew readline
brew reattach-to-user-namespace
brew rtmpdump
brew ruby
brew sphinx-doc
brew sqlite
brew tcl-tk
brew the_silver_searcher
brew tmux
brew unibilium
brew utf8proc
brew wget
brew xz
brew yarn
brew zstd

tap homebrew/bundle

tap homebrew/cask-fonts

tap homebrew/cask-versions
cask powershell-preview

tap homebrew/cask
cask alfred
cask discord
cask dotnet-sdk
cask gitter
cask iterm2
cask powershell
cask skype
cask slack
cask sourcetree
cask ubersicht
cask vagrant

tap argon/mas

tap neovim/neovim

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask hipchat

# App Store applications
appstore 1402042596  AdBlock                   (1.28.2)
appstore 1037126344  Apple Configurator 2      (2.14)
appstore 926036361   LastPass                  (4.4.0)
appstore 1295203466  Microsoft Remote Desktop  (10.6.7)
appstore 715768417   Microsoft Remote Desktop  (8.0.30030)
appstore 1274495053  Microsoft To Do           (2.47)
appstore 1176895641  Spark                     (2.10.0)
appstore 425424353   The Unarchiver            (4.3.3)
appstore 497799835   Xcode                     (12.5.1)
